### ISSUE TITLE
[v4dev] ToDo & pattern memo

### ISSUE THREAD

**Issue by 1natsu172** [1natsu172/Outside-YouTube-Player-Bar#73]
## navigation pattern

- [x] SPA navigation
  - [x] non-video page to video page
  - [x] video page to video page
- [x] direct access to video page with new tab

### special url case
- [x] `@username/live` | `username/live`
